name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@v7

      - name: Install node js
        uses: actions/setup-node@v6
        with:
          node-version: 20      

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: npm start &

      - name: check app health
        run: |
          curl -I "http://localhost:3000/health" || exit 1